variables:
  GOPATH: '$(Agent.BuildDirectory)/gopath' # Go workspace path
  GOROOT: '$(Agent.BuildDirectory)/go' # Go installation path
  GOBIN:  '$(GOPATH)/bin' # Go binaries path

steps:
- task: GoTool@0
  inputs:
    version: '1.13.5'
- task: Go@0
  inputs:
    command: 'get'
    arguments: '-d'
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      echo "Installing Dep"
      go get -u github.com/golang/dep/cmd/dep
      echo "Adding GOBIN to path: $env:GOBIN"
      $env:PATH += ":$env:GOBIN"
      echo "Added $env:GOBIN to path $env:PATH"
      go env
      
#dep ensure

